/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.javaserial;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author henrique2
 */
public class App extends javax.swing.JFrame {

    static ArrayList<Person> PersonAdd = new ArrayList<>();
    static ArrayList<Curso> CursoArray = new ArrayList<>();
    static ArrayList<Disciplina> DisciplinaArray = new ArrayList<>();
    static ArrayList<Inscricao> InscricaoArray = new ArrayList<>();
    static int idAluno = 1;
    static int idCursoarraylist = 1;
    static int idDisciplinaArray = 1;
    static int idInscricao = 1;

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        disciplinalabel1 = new javax.swing.JLabel();
        ano2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ano1 = new javax.swing.JTextField();
        disciplinalabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        inscricoestab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        nomelabel = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pais = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        altura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ano = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        restaurar = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        res = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cursoslabel = new javax.swing.JLabel();
        nomecurso = new javax.swing.JTextField();
        disciplinaslabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        disciplinas = new javax.swing.JTextField();
        horas = new javax.swing.JTextField();
        guardarcurso = new javax.swing.JButton();
        restaurarcurso = new javax.swing.JButton();
        limparcurso = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        rescurso = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        idcurso = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        disciplinalabel2 = new javax.swing.JLabel();
        disciplinatabdisciplina = new javax.swing.JTextField();
        guardardisciplina = new javax.swing.JButton();
        restaurardisciplina = new javax.swing.JButton();
        limpardisciplina = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        horasdadisciplina = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        iddisciplina = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        resdisciplina = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        idinscricao = new javax.swing.JTextField();
        nomedoalunoinscricao = new javax.swing.JTextField();
        cursoinscricao = new javax.swing.JTextField();
        guardarinscricao = new javax.swing.JButton();
        restaurarinscricao = new javax.swing.JButton();
        limparinscricao = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        resinscricao = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        disciplinalabel1.setText("Disciplina");

        jLabel4.setText("Curso");

        disciplinalabel.setText("Disciplina");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomelabel.setText("Nome  ");

        jLabel2.setText("País  ");

        jLabel3.setText("Altura");

        jLabel1.setText("Ano   ");

        jLabel14.setText("ID");

        id.setEditable(false);

        guardar.setText("Guardar Aluno");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        restaurar.setText("Restaurar Aluno");
        restaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurarActionPerformed(evt);
            }
        });

        limpar.setText("Limpar Aluno");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        res.setEditable(false);
        res.setColumns(20);
        res.setRows(5);
        jScrollPane1.setViewportView(res);

        jLabel7.setText("Logs");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(restaurar)
                                        .addGap(18, 18, 18)
                                        .addComponent(limpar)
                                        .addGap(7, 7, 7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(nomelabel)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel14))
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 281, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomelabel)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar)
                    .addComponent(restaurar)
                    .addComponent(limpar))
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );

        inscricoestab.addTab("Aluno", jPanel1);

        cursoslabel.setText("Curso");

        nomecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomecursoActionPerformed(evt);
            }
        });

        disciplinaslabel.setText("Disciplinas");

        jLabel5.setText("Horas");

        disciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disciplinasActionPerformed(evt);
            }
        });

        horas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horasActionPerformed(evt);
            }
        });

        guardarcurso.setText("Guardar Curso");
        guardarcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarcursoActionPerformed(evt);
            }
        });

        restaurarcurso.setText("Restaurar Curso");
        restaurarcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurarcursoActionPerformed(evt);
            }
        });

        limparcurso.setText("Limpar Curso");
        limparcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparcursoActionPerformed(evt);
            }
        });

        rescurso.setEditable(false);
        rescurso.setColumns(20);
        rescurso.setRows(5);
        jScrollPane4.setViewportView(rescurso);

        jLabel17.setText("Logs");

        jLabel10.setText("ID");

        idcurso.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(disciplinaslabel)
                                    .addComponent(jLabel5)
                                    .addComponent(cursoslabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(idcurso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                        .addComponent(horas, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(disciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(guardarcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(restaurarcurso)
                                .addGap(18, 18, 18)
                                .addComponent(limparcurso, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                        .addGap(274, 274, 274))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel17)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursoslabel)
                    .addComponent(nomecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disciplinaslabel)
                    .addComponent(disciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(idcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarcurso)
                    .addComponent(restaurarcurso)
                    .addComponent(limparcurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        inscricoestab.addTab("Curso", jPanel2);

        disciplinalabel2.setText("Disciplina");

        disciplinatabdisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disciplinatabdisciplinaActionPerformed(evt);
            }
        });

        guardardisciplina.setText("Guardar Disciplina");
        guardardisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardardisciplinaActionPerformed(evt);
            }
        });

        restaurardisciplina.setText("Restaurar Disciplina");
        restaurardisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurardisciplinaActionPerformed(evt);
            }
        });

        limpardisciplina.setText("Limpar Disciplina");
        limpardisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpardisciplinaActionPerformed(evt);
            }
        });

        jLabel6.setText("Horas");

        jLabel15.setText("ID");

        iddisciplina.setEditable(false);

        jLabel18.setText("Logs");

        resdisciplina.setEditable(false);
        resdisciplina.setColumns(20);
        resdisciplina.setRows(5);
        jScrollPane5.setViewportView(resdisciplina);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane5)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(guardardisciplina)
                        .addGap(18, 18, 18)
                        .addComponent(restaurardisciplina)
                        .addGap(18, 18, 18)
                        .addComponent(limpardisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(260, 260, 260))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(disciplinalabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(disciplinatabdisciplina, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(iddisciplina, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                        .addComponent(horasdadisciplina, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel18)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disciplinalabel2)
                    .addComponent(disciplinatabdisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(horasdadisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(iddisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardardisciplina)
                    .addComponent(restaurardisciplina)
                    .addComponent(limpardisciplina))
                .addGap(29, 29, 29)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        inscricoestab.addTab("Disciplina", jPanel3);

        jLabel8.setText("ID");

        jLabel9.setText("Nome");

        jLabel13.setText("Curso");

        idinscricao.setEditable(false);

        guardarinscricao.setText("Guardar Inscrição");
        guardarinscricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarinscricaoActionPerformed(evt);
            }
        });

        restaurarinscricao.setText("Restaurar Inscrição");
        restaurarinscricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurarinscricaoActionPerformed(evt);
            }
        });

        limparinscricao.setText("Limpar Inscrição");
        limparinscricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparinscricaoActionPerformed(evt);
            }
        });

        jLabel19.setText("Logs");

        resinscricao.setEditable(false);
        resinscricao.setColumns(20);
        resinscricao.setRows(5);
        jScrollPane6.setViewportView(resinscricao);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel8))
                                    .addGap(20, 20, 20)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(idinscricao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nomedoalunoinscricao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(19, 19, 19)
                                    .addComponent(cursoinscricao)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(guardarinscricao)
                                .addGap(18, 18, 18)
                                .addComponent(restaurarinscricao)
                                .addGap(18, 18, 18)
                                .addComponent(limparinscricao))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel19)))
                        .addGap(0, 250, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(idinscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nomedoalunoinscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cursoinscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarinscricao)
                    .addComponent(restaurarinscricao)
                    .addComponent(limparinscricao))
                .addGap(32, 32, 32)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        inscricoestab.addTab("Inscrições", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inscricoestab)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(inscricoestab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardardisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardardisciplinaActionPerformed
        // TODO add your handling code here:
        Disciplina disciplina = new Disciplina();
        disciplina.setDisciplinatabdisciplina(disciplinatabdisciplina.getText());
        disciplina.setIddisciplina(idDisciplinaArray++);
        disciplina.setHorasdadisciplina(Integer.parseInt(horasdadisciplina.getText()));
        try {
            DisciplinaArray.add(disciplina);
            FileOutputStream fileOutputStream = new FileOutputStream("C:\\Users\\Henrique\\AppData\\Local\\Temp\\disciplina.txt");
            ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream);
            objectOutputStream.writeObject(DisciplinaArray);
            fileOutputStream.close();
            objectOutputStream.close();
            for (Disciplina DisciplinaArray : DisciplinaArray) {
            }
            objectOutputStream.close();
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guardardisciplinaActionPerformed

    private void restaurardisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurardisciplinaActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            FileInputStream fileinputDisciplina = new FileInputStream("C:\\Users\\Henrique\\AppData\\Local\\Temp\\disciplina.txt");
            ObjectInputStream objectinputDisciplina = new ObjectInputStream(fileinputDisciplina);
            DisciplinaArray = (ArrayList<Disciplina>) objectinputDisciplina.readObject();
            objectinputDisciplina.close();
            fileinputDisciplina.close();
            for (Disciplina DisciplinaArray : DisciplinaArray) {
                idDisciplinaArray = DisciplinaArray.getIddisciplina();
                resdisciplina.append(DisciplinaArray.toString());
            }
            idDisciplinaArray++;
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_restaurardisciplinaActionPerformed

    private void limpardisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpardisciplinaActionPerformed
        // TODO add your handling code here:
        iddisciplina.setText("");
        disciplinatabdisciplina.setText("");
        horasdadisciplina.setText("");
        resdisciplina.setText("");
    }//GEN-LAST:event_limpardisciplinaActionPerformed

    private void guardarinscricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarinscricaoActionPerformed
        FileInputStream fileinputInscricao = null;
        try {
            // TODO add your handling code here:
            Inscricao inscricao = new Inscricao();
            fileinputInscricao = new FileInputStream("C:\\Users\\Henrique\\AppData\\Local\\Temp\\inscricao.txt");
            fileinputInscricao.close();
            ObjectInputStream objectinputInscricao = new ObjectInputStream(fileinputInscricao);
            objectinputInscricao.close();
            int Alunoid = Integer.parseInt(nomedoalunoinscricao.getText());
            int Cursoid = Integer.parseInt(cursoinscricao.getText());
            inscricao.setCursoinscricao(String.valueOf(Cursoid));
            inscricao.setNomedoalunoinscricao(String.valueOf(Alunoid));
            Curso cursos = CursoArray.get(Cursoid - 1);
            inscricao.setCursoinscricao(cursos.getNomecurso());
            Person person = PersonAdd.get(Alunoid - 1);
            inscricao.setNomedoalunoinscricao(person.getNome());
            InscricaoArray.add(inscricao);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileinputInscricao.close();
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_guardarinscricaoActionPerformed

    private void restaurarinscricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurarinscricaoActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            FileInputStream fileinputInscricao = new FileInputStream("C:\\Users\\Henrique\\AppData\\Local\\Temp\\inscricao.txt");
            ObjectInputStream objectinputInscricao = new ObjectInputStream(fileinputInscricao);
            InscricaoArray = (ArrayList<Inscricao>) objectinputInscricao.readObject();
            objectinputInscricao.close();
            fileinputInscricao.close();
            for (Inscricao InscricaoArray : InscricaoArray) {
                idInscricao = InscricaoArray.getIdinscricao();
                resinscricao.append(InscricaoArray.toString());
            }
            idInscricao++;
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_restaurarinscricaoActionPerformed

    private void limparinscricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparinscricaoActionPerformed
        // TODO add your handling code here:
        idinscricao.setText("");
        nomedoalunoinscricao.setText("");
        cursoinscricao.setText("");
        resinscricao.setText("");
    }//GEN-LAST:event_limparinscricaoActionPerformed

    private void limparcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparcursoActionPerformed
        // TODO add your handling code here:
        nomecurso.setText("");
        disciplinas.setText("");
        horas.setText("");
        rescurso.setText("");
        idcurso.setText("");
    }//GEN-LAST:event_limparcursoActionPerformed

    private void restaurarcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurarcursoActionPerformed
        FileInputStream fileinputCurso = null;
        try {
            // TODO add your handling code here:
            fileinputCurso = new FileInputStream("C:\\Users\\Henrique\\AppData\\Local\\Temp\\curso.txt");
            ObjectInputStream objectinputCurso = new ObjectInputStream(fileinputCurso);
            CursoArray = (ArrayList<Curso>) objectinputCurso.readObject();
            objectinputCurso.close();
            fileinputCurso.close();
            for (Curso CursoArray : CursoArray) {
                idCursoarraylist = CursoArray.getIdcurso();
                rescurso.append(CursoArray.toString());
            }
            idCursoarraylist++;
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileinputCurso.close();
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_restaurarcursoActionPerformed

    private void guardarcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarcursoActionPerformed
        // TODO add your handling code here:

        Curso curso = new Curso();
        curso.setNomecurso(nomecurso.getText());
        curso.setIdcurso(idCursoarraylist++);
        curso.setHoras(Integer.parseInt(horas.getText()));
        curso.setDisciplina(disciplinas.getText());
        try {
            CursoArray.add(curso);
            FileOutputStream fileOutputStream = new FileOutputStream("C:\\Users\\Henrique\\AppData\\Local\\Temp\\curso.txt");
            ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream);
            objectOutputStream.writeObject(CursoArray);
            fileOutputStream.close();
            objectOutputStream.close();
            for (Curso CursoArray : CursoArray) {
                rescurso.setText(CursoArray.toString());
            }
            objectOutputStream.close();
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guardarcursoActionPerformed

    private void horasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horasActionPerformed

    private void disciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disciplinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disciplinasActionPerformed

    private void nomecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomecursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomecursoActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        // TODO add your handling code here:
        nome.setText("");
        pais.setText("");
        altura.setText("");
        ano.setText("");
        id.setText("");
        res.setText("");
    }//GEN-LAST:event_limparActionPerformed

    private void restaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurarActionPerformed

       try {
            // TODO add your handling code here:
            FileInputStream fileinputPerson = new FileInputStream("C:\\Users\\Henrique\\AppData\\Local\\Temp\\person.txt");
            ObjectInputStream objectinputPerson = new ObjectInputStream(fileinputPerson);
            PersonAdd = (ArrayList<Person>) objectinputPerson.readObject();
            objectinputPerson.close();
            fileinputPerson.close();
            for (Person PersonAdd : PersonAdd) {
                idAluno = PersonAdd.getId();
                res.append(PersonAdd.toString());
            }
            idAluno++;
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }//GEN-LAST:event_restaurarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        Person person = new Person();
        person.setNome(nome.getText());
        person.setAno(Integer.parseInt(ano.getText()));
        person.setPais(pais.getText());
        person.setAltura(Integer.parseInt(altura.getText()));
        person.setId(idAluno++);
            try {
                PersonAdd.add(person);
                ObjectOutputStream objectOutputStream;
                try (FileOutputStream fileOutputStream = new FileOutputStream("C:\\Users\\Henrique\\AppData\\Local\\Temp\\person.txt")) {
                    objectOutputStream = new ObjectOutputStream(fileOutputStream);
                    objectOutputStream.writeObject(PersonAdd);
                }
                objectOutputStream.close();
                for (Person PersonAdd : PersonAdd) {
                    res.setText(PersonAdd.toString());
                }

                objectOutputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_guardarActionPerformed

    private void disciplinatabdisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disciplinatabdisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disciplinatabdisciplinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altura;
    private javax.swing.JTextField ano;
    private javax.swing.JTextField ano1;
    private javax.swing.JTextField ano2;
    private javax.swing.JTextField cursoinscricao;
    private javax.swing.JLabel cursoslabel;
    private javax.swing.JLabel disciplinalabel;
    private javax.swing.JLabel disciplinalabel1;
    private javax.swing.JLabel disciplinalabel2;
    private javax.swing.JTextField disciplinas;
    private javax.swing.JLabel disciplinaslabel;
    private javax.swing.JTextField disciplinatabdisciplina;
    private javax.swing.JButton guardar;
    private javax.swing.JButton guardarcurso;
    private javax.swing.JButton guardardisciplina;
    private javax.swing.JButton guardarinscricao;
    private javax.swing.JTextField horas;
    private javax.swing.JTextField horasdadisciplina;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idcurso;
    private javax.swing.JTextField iddisciplina;
    private javax.swing.JTextField idinscricao;
    private javax.swing.JTabbedPane inscricoestab;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton limpar;
    private javax.swing.JButton limparcurso;
    private javax.swing.JButton limpardisciplina;
    private javax.swing.JButton limparinscricao;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField nomecurso;
    private javax.swing.JTextField nomedoalunoinscricao;
    private javax.swing.JLabel nomelabel;
    private javax.swing.JTextField pais;
    private javax.swing.JTextArea res;
    private javax.swing.JTextArea rescurso;
    private javax.swing.JTextArea resdisciplina;
    private javax.swing.JTextArea resinscricao;
    private javax.swing.JButton restaurar;
    private javax.swing.JButton restaurarcurso;
    private javax.swing.JButton restaurardisciplina;
    private javax.swing.JButton restaurarinscricao;
    // End of variables declaration//GEN-END:variables
}
